import turtle
tao = turtle.Pen()
turtle.speed("fast")
tao.shape('turtle')
turtle.bgcolor('white')
for i in range (72):
    tao.goto(0,0)
    tao.pensize(5)
    tao.color('yellow')
    tao.circle(300)
    tao.left(5)
    tao.goto(2,2)
tao.penup()
tao.goto(0, 0)
tao.pendown()
for i in range (180):
    tao.pensize(5)
    tao.color('red')
    tao.circle(300)
    tao.left(2)
tao.penup()
tao.goto(0, 0)
tao.pendown()
for i in range (36):
    tao.pensize(5)
    tao.color('blue')
    tao.circle(300)
    tao.left(10)
tao.penup()
tao.goto(0, 0)
tao.pendown()
for i in range (360):
    tao.pensize(2)
    tao.color('white')
    tao.circle(10)
    tao.left(1)
done()
